server:
 port: 8082
 error:
  include-message: always
  include-binding-errors: always
  #include-stacktrace: on_trace_param
  include-exception: false
  
spring:
  application:
    name: flight-admin-service
  datasource:
    url: jdbc:mysql://localhost:3306/flight_db?useSSL=false
    username: root
    password: root

    
#actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,env,beans
  info:
    env:
      enabled: true

info:
  application:
    name: ${spring.application.name}
    description: Very cool Spring Boot application
    version: '@project.version@'
    spring-cloud-version: '@spring-cloud.version@'
    spring-boot-version: '@project.parent.version@'
  