server:
  port: 8087
  
spring:
  application:
    name: flight-booking-service
  datasource:
    url: jdbc:mysql://localhost:3306/flight_booking_db?useSSL=false
    username: root
    password: root
    
    
#actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,env,beans
  info:
    env:
      enabled: true

info:
  application:
    name: ${spring.application.name}
    description: Very cool Spring Boot application
    version: '@project.version@'
    spring-cloud-version: '@spring-cloud.version@'
    spring-boot-version: '@project.parent.version@'
  
